# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20171117_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='username',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
